// ============================================================
// Haldwani, Uttarakhand — Demo Property Seed Data
// Used when Supabase is not configured (mock mode)
// ============================================================

export const DEMO_PROPERTIES = [
  {
    id: 'p-hld-001',
    property_id: 'HLD-PRC-2024-001',
    v_ulpin: 'VULPIN-UK-ND44-A1B2C3-G-101',
    ulpin: 'UK-2024-001-ND-HLD',
    owner_name: 'Rajendra Singh Bisht',
    property_type: 'Residential',
    address: 'Plot 12, Banbhoolpura, Haldwani, Nainital, Uttarakhand 263139',
    latitude: 29.2183, longitude: 79.5130, elevation: 454,
    land_area: '320 sq.m', built_up_area: '210 sq.m', floors: 2,
    occupancy_status: 'Occupied', construction_year: 2015,
    verification_status: 'Verified',
  },
  {
    id: 'p-hld-002',
    property_id: 'HLD-PRC-2023-042',
    v_ulpin: 'VULPIN-UK-ND44-D4E5F6-G-201',
    ulpin: 'UK-2023-042-ND-HLD',
    owner_name: 'Meena Arya Enterprises',
    property_type: 'Commercial',
    address: 'Shop 8, Bazaar Road, Bankhandi, Haldwani, Nainital 263139',
    latitude: 29.2241, longitude: 79.5189, elevation: 460,
    land_area: '580 sq.m', built_up_area: '420 sq.m', floors: 4,
    occupancy_status: 'Occupied', construction_year: 2010,
    verification_status: 'Pending',
  },
  {
    id: 'p-hld-003',
    property_id: 'HLD-PRC-2024-015',
    v_ulpin: 'VULPIN-UK-ND44-G7H8I9-G-301',
    ulpin: 'UK-2024-015-ND-HLD',
    owner_name: 'Durga Prasad Joshi',
    property_type: 'Mixed-Use',
    address: 'Survey 112/C, Gaujajali, Haldwani, Nainital 263139',
    latitude: 29.2120, longitude: 79.5075, elevation: 448,
    land_area: '750 sq.m', built_up_area: '560 sq.m', floors: 3,
    occupancy_status: 'Occupied', construction_year: 2012,
    verification_status: 'Verified',
  },
  {
    id: 'p-hld-004',
    property_id: 'HLD-PRC-2022-087',
    v_ulpin: 'VULPIN-UK-ND44-J1K2L3-G-401',
    ulpin: 'UK-2022-087-ND-HLD',
    owner_name: 'Pahadi Industries Pvt. Ltd.',
    property_type: 'Industrial',
    address: 'Sheetla Chowk Industrial Area, Haldwani, Nainital 263139',
    latitude: 29.2310, longitude: 79.5240, elevation: 462,
    land_area: '1200 sq.m', built_up_area: '950 sq.m', floors: 1,
    occupancy_status: 'Occupied', construction_year: 2008,
    verification_status: 'Verified',
  },
  {
    id: 'p-hld-005',
    property_id: 'HLD-PRC-2024-033',
    v_ulpin: null,
    ulpin: 'UK-2024-033-ND-HLD',
    owner_name: 'Savitri Devi Pant',
    property_type: 'Residential',
    address: 'Plot 55, Rampur Road, Haldwani, Nainital 263139',
    latitude: 29.2150, longitude: 79.5220, elevation: 450,
    land_area: '280 sq.m', built_up_area: '190 sq.m', floors: 2,
    occupancy_status: 'Under Construction', construction_year: 2024,
    verification_status: 'Pending',
  },
  {
    id: 'p-hld-006',
    property_id: 'HLD-PRC-2023-071',
    v_ulpin: 'VULPIN-UK-ND44-M4N5O6-G-601',
    ulpin: 'UK-2023-071-ND-HLD',
    owner_name: 'Himalayan Trading Co.',
    property_type: 'Commercial',
    address: 'Transport Nagar, Haldwani, Nainital 263139',
    latitude: 29.2270, longitude: 79.5160, elevation: 456,
    land_area: '490 sq.m', built_up_area: '380 sq.m', floors: 3,
    occupancy_status: 'Occupied', construction_year: 2014,
    verification_status: 'Rejected',
  },
  {
    id: 'p-hld-007',
    property_id: 'HLD-PRC-2024-099',
    v_ulpin: 'VULPIN-UK-ND44-P7Q8R9-G-701',
    ulpin: 'UK-2024-099-ND-HLD',
    owner_name: 'Mohan Lal Tewari',
    property_type: 'Agricultural',
    address: 'Kathgodam Agricultural Zone, Haldwani, Nainital 263139',
    latitude: 29.2055, longitude: 79.5280, elevation: 444,
    land_area: '2400 sq.m', built_up_area: '120 sq.m', floors: 1,
    occupancy_status: 'Occupied', construction_year: 2000,
    verification_status: 'Verified',
  },
  {
    id: 'p-hld-008',
    property_id: 'HLD-PRC-2023-055',
    v_ulpin: null,
    ulpin: 'UK-2023-055-ND-HLD',
    owner_name: 'Geeta Rawat',
    property_type: 'Residential',
    address: 'Sector 4, Indira Nagar, Haldwani, Nainital 263139',
    latitude: 29.2198, longitude: 79.5095, elevation: 452,
    land_area: '200 sq.m', built_up_area: '160 sq.m', floors: 1,
    occupancy_status: 'Vacant', construction_year: 2019,
    verification_status: 'Pending',
  },
  {
    id: 'p-hld-009',
    property_id: 'HLD-PRC-2022-018',
    v_ulpin: 'VULPIN-UK-ND44-S1T2U3-G-901',
    ulpin: 'UK-2022-018-ND-HLD',
    owner_name: 'Ramesh Chandra Negi',
    property_type: 'Residential',
    address: 'Mukhani Road, Haldwani, Nainital 263139',
    latitude: 29.2330, longitude: 79.5180, elevation: 465,
    land_area: '370 sq.m', built_up_area: '290 sq.m', floors: 3,
    occupancy_status: 'Occupied', construction_year: 2011,
    verification_status: 'Verified',
  },
  {
    id: 'p-hld-010',
    property_id: 'HLD-PRC-2024-076',
    v_ulpin: null,
    ulpin: 'UK-2024-076-ND-HLD',
    owner_name: 'Prem Kumar Sharma',
    property_type: 'Commercial',
    address: 'Mall Road, Haldwani, Nainital 263139',
    latitude: 29.2210, longitude: 79.5145, elevation: 455,
    land_area: '620 sq.m', built_up_area: '510 sq.m', floors: 5,
    occupancy_status: 'Disputed', construction_year: 2016,
    verification_status: 'Rejected',
  },
];

export function getAnalyticsFromMock() {
  const total = DEMO_PROPERTIES.length;
  const verified = DEMO_PROPERTIES.filter(p => p.verification_status === 'Verified').length;
  const pending  = DEMO_PROPERTIES.filter(p => p.verification_status === 'Pending').length;
  const rejected = DEMO_PROPERTIES.filter(p => p.verification_status === 'Rejected').length;
  const totalBuildings = total; // 1 building per property in demo
  const totalUnits = DEMO_PROPERTIES.reduce((s, p) => s + p.floors * 2, 0);
  return { total, verified, pending, rejected, totalBuildings, totalUnits };
}
